### ISSUE TITLE
Open file types in the Oxygen 

### ISSUE THREAD

**Issue by BlueCC8** [AlexJitianu/oxygen-cmis-plugin#1]
## API issues

* There is no method that returns what filetypes are supported in the **MAIN_EDITING_AREA** and by what editors;
* Method `pluginWorkspace.open()` doesn't check for the supported file types;
* Method `pluginWorkspace.openInExternalApplication()` needs an absolute path that is not available because Oxygen uses a custom url with a custom protocol.

## Task List
- [x] Character type files are all supported;
- [ ] Get the files supported in the **MAIN_EDITING_AREA** and **DITA_MAPS_EDITING_AREA**;
- [ ] Get the files supported only in the preview mode (images for example);
- [ ] Get the absolute path of a file using the custom url and the protocol.
